export const ComplaintStateEnum = Object.freeze({
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  READY_FOR_ASSIGNMENT: 'READY_FOR_ASSIGNMENT',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  WORK_COMPLETED: 'WORK_COMPLETED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFIED: 'VERIFIED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  REASSIGNED: 'REASSIGNED',
  ESCALATED: 'ESCALATED',
  CANCELLED: 'CANCELLED',
});

export default ComplaintStateEnum;
