export const OrchestratorConfig = Object.freeze({
  MAX_RETRIES: 2,
  BACKOFF_BASE_MS: 200,
  WORKFLOW_STATUSES: {
    CREATED: 'CREATED',
    TRIAGE_PARALLEL: 'TRIAGE_PARALLEL',
    DUPLICATE_CHECK: 'DUPLICATE_CHECK',
    COMMUNITY_VALIDATION: 'COMMUNITY_VALIDATION',
    PRIORITY_ASSESSMENT: 'PRIORITY_ASSESSMENT',
    DEPARTMENT_RECOMMENDATION: 'DEPARTMENT_RECOMMENDATION',
    OUTPUT_MERGED: 'OUTPUT_MERGED',
    EVENT_PUBLISHED: 'EVENT_PUBLISHED',
    GOVERNMENT_HANDOVER: 'GOVERNMENT_HANDOVER',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
  },
  EVENT_TYPES: {
    WORKFLOW_STARTED: 'WorkflowStarted',
    AGENT_STEP_COMPLETED: 'AgentStepCompleted',
    WORKFLOW_COMPLETED: 'WorkflowCompleted',
    GOVERNMENT_HANDOVER_SUCCESS: 'GovernmentHandoverSuccess',
  },
});

export default OrchestratorConfig;
