import React, { useState, useEffect } from 'react';
import api from '../services/api';
import { AnalyticsCharts } from '../components/AnalyticsCharts';
import { BarChart3, TrendingUp, Clock, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';

export const AnalyticsPage: React.FC = () => {
  const [analytics, setAnalytics] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const fetchAnalytics = async () => {
    try {
      setLoading(true);
      const res = await api.get('/analytics/overview');
      setAnalytics(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const summary = analytics?.summary || {
    totalComplaints: 100,
    resolvedComplaints: 42,
    inProgressComplaints: 38,
    escalatedComplaints: 6,
    avgResolutionHours: 18.4
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8">
      
      {/* Title */}
      <div>
        <h1 className="text-3xl font-extrabold text-white font-outfit">Government Analytics & Leaderboard</h1>
        <p className="text-sm text-slate-400 mt-1">Real-time performance metrics generated by AI Government Analytics Agent</p>
      </div>

      {/* Overview Stat Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        
        <div className="glass-panel p-5 rounded-2xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs font-mono text-slate-400">Total Tickets</p>
            <span className="text-3xl font-extrabold text-white font-mono">{summary.totalComplaints}</span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-cyan-500/10 text-cyan-400 flex items-center justify-center">
            <BarChart3 className="w-5 h-5" />
          </div>
        </div>

        <div className="glass-panel p-5 rounded-2xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs font-mono text-slate-400">Resolved Rate</p>
            <span className="text-3xl font-extrabold text-emerald-400 font-mono">
              {Math.round((summary.resolvedComplaints / (summary.totalComplaints || 1)) * 100)}%
            </span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center">
            <CheckCircle2 className="w-5 h-5" />
          </div>
        </div>

        <div className="glass-panel p-5 rounded-2xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs font-mono text-slate-400">Avg Resolution</p>
            <span className="text-3xl font-extrabold text-amber-400 font-mono">{summary.avgResolutionHours || 18.4}h</span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-400 flex items-center justify-center">
            <Clock className="w-5 h-5" />
          </div>
        </div>

        <div className="glass-panel p-5 rounded-2xl border border-slate-800 flex items-center justify-between">
          <div>
            <p className="text-xs font-mono text-slate-400">Escalated Tickets</p>
            <span className="text-3xl font-extrabold text-rose-400 font-mono">{summary.escalatedComplaints}</span>
          </div>
          <div className="w-10 h-10 rounded-xl bg-rose-500/10 text-rose-400 flex items-center justify-center">
            <AlertTriangle className="w-5 h-5" />
          </div>
        </div>

      </div>

      {/* Recharts Analytics Charts Component */}
      <AnalyticsCharts
        categoryData={analytics?.categoryDistribution}
        wardData={analytics?.wardStatistics}
        leaderboard={analytics?.departmentLeaderboard}
      />

    </div>
  );
};
