export const WorkProgressStateEnum = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  ON_THE_WAY: 'ON_THE_WAY',
  INSPECTION_IN_PROGRESS: 'INSPECTION_IN_PROGRESS',
  REPAIR_IN_PROGRESS: 'REPAIR_IN_PROGRESS',
  WAITING_FOR_RESOURCES: 'WAITING_FOR_RESOURCES',
  WORK_COMPLETED: 'WORK_COMPLETED',
});

export default WorkProgressStateEnum;
