export const NotificationTypeEnum = Object.freeze({
  COMPLAINT_SUBMITTED: 'COMPLAINT_SUBMITTED',
  COMPLAINT_ACCEPTED: 'COMPLAINT_ACCEPTED',
  OFFICER_ASSIGNED: 'OFFICER_ASSIGNED',
  WORK_STARTED: 'WORK_STARTED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
  ESCALATION_ALERT: 'ESCALATION_ALERT',
  REWORK_REQUESTED: 'REWORK_REQUESTED',
  COMPLAINT_CLOSED: 'COMPLAINT_CLOSED',
  GENERAL_ANNOUNCEMENT: 'GENERAL_ANNOUNCEMENT',
});

export default NotificationTypeEnum;
